### ISSUE TITLE
Multiple versions of Stata?

### ISSUE THREAD

**Issue by mbaker21231** [TiesdeKok/ipystata#11]
Hi Ties --

First, everything is working great - I really like `ipystata`! In any case, I just had a quick question about multiple versions of `Stata` and using `ipystata`. As it happens, I have both `Stata 12` and `Stata 14` on my computer. While I usually use `Stata 12` (because it is version SE), I use some new packages like `teffects` with `Stata 14`. Is there a way to toggle between versions? If not, can I just register rerun the registration steps with `ipystata` without damaging anything? 

All the best,

Matt

**Comment by TiesdeKok** [comment]
Hi Matt,

Great to hear, glad you enjoy using it!

The version of Stata that IPyStata communicates with is directly imposed by Windows (similar to an environmental variable). Additionally, to my knowledge there can only be one Stata version "registered" at a time. So within IPyStata it cannot toggle between different versions. 

However, you should be able to `/Unregister` your current Stata version and `/Register` a different version. (See 3.1 here: http://www.stata.com/automation/#createmsapp). I have done it in the past to see whether it worked under both Stata 13 and Stata 14, I cannot recall however whether I had to restart my computer or whether it would just all work at once. I do remember that the `/Unregister` part was important for it to successfully change the version. 

If you need to frequently change between versions it might be worthwhile to check whether it is possible to write a batch script that will automatically `/Deregister` one version and `/Register` the other.  I haven't tried whether this is possible but I think you should be able to write on relatively easily.

**Comment by mbaker21231** [comment]
Ties --

Sounds good.

Best,

Matt
