### ISSUE TITLE
Stata14 in Linux with wine

### ISSUE THREAD

**Issue by mbaker21231** [TiesdeKok/ipystata#13]
Hi Ties --

I hope all is well. I'm writing just to put something on your radar screen. At my place of employment, we don't have Stata14 in Linux format, but I switched anyways. As it happens, there is a program called `wine` that can run `.exe` files in Linux, and it works very nicely with Stata. 

Anyways, my question is as follows: while you say that `ipystata` will not work in interactive mode with linux, is it possible that `ipystata` running an `.exe` file through `wine` in linux might? 

Just curious what your thoughts are.

Matt

**Comment by TiesdeKok** [comment]
Hi Matt,

I have encountered other people that were using a similar setup. It is unfortunate that the Stata 14 installation files are not easily available for multiple platforms, especially given that most Stata licenses are not platform specific (as far as I know). 

It is definitely an interesting thought to utilize `wine` to enable interactive mode with `ipystata`. Unfortunately, I am fairly certain that it will not work. The interactivity flows through functionality of the Windows operation system (called `Windows Automation API`), this is lacking on a Unix based OS. 

I have been playing with the idea of using Stata in so-called "interactive console mode" to provide interactivity for `ipystata` on unix systems. However, I haven't looked at the whether it is possible and feasible to program communication with such a console instance. 

In a month I will be talking about `ipystata` during the 2016 Stata Conference, maybe the Stata engineers can help me figure out the best way to achieve this. :smile:

**Comment by mbaker21231** [comment]
Ties --

I see - I didn't know that that was how and why it worked with windows, and I can see you have thought about this in more depth than I! It will be interesting to see what the folks at the conference have to say about this. 

Best,

Matt
