### ISSUE TITLE
great work !!!!!

### ISSUE THREAD

**Issue by randomgambit** [TiesdeKok/ipystata#16]
Hi TiesdeKok,

I just discovered by chance your ipystata package and I just wanted to tell you **# THAT S AMAZING**!
I am a econ PhD and I use python, stata all the time. Your packages is great to share code and regressions using jupyter notebooks.

Keep up the great work!

**Comment by TiesdeKok** [comment]
Thanks a lot for the kinds words, I am very glad to hear that other people enjoy using it as much as I like using it myself! :smiley:
