### ISSUE TITLE
send a dataframe?

### ISSUE THREAD

**Issue by randomgambit** [TiesdeKok/ipystata#17]
actually I have a question. 

I see that you can send a dataframe to stata and get back some data from Stata. How do you do that? Are you using the to_stata method in Pandas? And for the other way around?

This is a very useful function, but it can be very tricky. What about the dtypes? How does it work?

Thanks

**Comment by TiesdeKok** [comment]
Yes, I have written some code to modify any dates in the dataframe to something that Stata can understand and then I use the `to_stata` method from Pandas to save it as a .dta file. I then send some boilerplate commands to Stata to load this temporary .dta file. 

For returning the Stata data back from Stata to Python I have Stata save the dataset to another temporary .dta file and have Python load it back into memory using the Pandas `read_stata` function. 

You are right that dtypes can be tricky, I currently rely for the most part on the .dta conversion from Pandas with the exception of handling dates. 

For my use cases I have not experienced any dtype problems but if you encounter any please let me know. It should be possible to include a routine in my code that improves the conversion for those cases.

**Comment by randomgambit** [comment]
OK I see. 

You might find useful this thing I noticed some time ago https://github.com/pydata/pandas/issues/12259

I ll let you know if I find something

Thanks!
