### ISSUE TITLE
python 3.k ipython 4.1 import error

### ISSUE THREAD

**Issue by asdf8601** [TiesdeKok/ipystata#2]
Hi, 
I try import the package in my notebook but i get this traceback:

``` python
import ipystata
from ipystata.ipystata_magic import iPyStata

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a1c00eb430f5> in <module>()
----> 1 import ipystata
      2 from ipystata.ipystata_magic import iPyStata

/Users/mmngreco/Virtualenvs/ipynb/lib/python3.5/site-packages/ipystata/__init__.py in <module>()
----> 1 import ipystata_magic

ImportError: No module named 'ipystata_magic'
```

**Comment by TiesdeKok** [comment]
I have previously only used / tested it in Python 2.7, when I try to import ipystata on my own Python 3.4 installation I get the same error. I will try to find some time to make my code compatible with Python 3.k.

Thanks for letting me know!

**Comment by TiesdeKok** [comment]
I have uploaded a  new version (0.1.4) to PyPi en Github, this version works with Python 2 and Python 3.

**Comment by asdf8601** [comment]
Thanks, now import correctly!
