### ISSUE TITLE
Necessity of pywin32 package?

### ISSUE THREAD

**Issue by bquistorff** [TiesdeKok/ipystata#24]
When trying to use the first time, I got an error when trying to import `ipystata` that `win32com` could not be imported. Everything worked great after I installed the `pywin32` package. I'm not sure if this was specific to me or if `pywin32` should be listed as a dependency on Windows. FWIW, I was using an Anaconda 4 distribution with a Python 3.5 environment on Windows 10 and I had installed `ipystata` using `pip`.

**Comment by TiesdeKok** [comment]
Thanks a lot for the heads-up! To my knowledge `pywin32` should come with the Windows Anaconda distribution by default. However, to prevent any confusion in the future I will update the README to include a list of all the dependencies including the less notable (but still important) ones like `pywin32`.
