### ISSUE TITLE
Please make ipystata+jupyter display Chinese characters  properly~~

### ISSUE THREAD

**Issue by lianyonghui123** [TiesdeKok/ipystata#28]
as we know, in Stata 14  , even the variable names can be Chinese characters ,but  Ipystata cannot display those names properly.  Hope you  will fix this minior problem in the future.
-----------------------------
ipystata is  a really GREAT thing!

**Comment by TiesdeKok** [comment]
Thanks for letting me know, I will look into it!

**Comment by TiesdeKok** [comment]
Hi @lianyonghui123, I looked into your problem and unfortunately it is not something that I can easily fix. The problem stems from the limited available encoding options by the Pandas `read_stata` and `to_stata` operations. I have reported this to the corresponding issue thread:

https://github.com/pandas-dev/pandas/issues/15723

**Comment by kylebarron** [comment]
With Pandas >= 0.23 I believe they added unicode support to [read_stata](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_stata.html?highlight=read_stata#pandas.read_stata)

Unicode still isn't supported by the writer though
