### ISSUE TITLE
what happens to log files?

### ISSUE THREAD

**Issue by kflamm** [TiesdeKok/ipystata#29]
Thanks for developing ipystata, it's a great idea.
When I run the %%stata cell and attempt to start up a log file inside the cell, I get the message "log file already open r(604);"
Any idea what's going on? Is there another log file that is opened by default when %%stata is invoked in Python? If so, how do I access it?

Thanks!

**Comment by kflamm** [comment]
Sorry, figured out the issue....

putting "import os" in the cell above seems to solve the problem, I'm finding a log file now.

Thanks!

**Comment by TiesdeKok** [comment]
Sorry for my delayed reaction, I was on holiday. Good to hear that it works now, I will keep your report in the back of my mind. Next time I go through my code I will investigate why adding `import os` seemed to have fixed the problem.
