### ISSUE TITLE
Problem with syntax highlighting

### ISSUE THREAD

**Issue by v-marinkov** [TiesdeKok/ipystata#32]
Hi Ties, thanks for your great work!
I just tried to implement your instructions for the STATA-style syntax highlighting, but I get the following error:
![image](https://user-images.githubusercontent.com/7135724/38804897-451cd088-4174-11e8-90f5-a3128b1063b9.png)

Here is where my Anaconda installation resides and where I put the `stata.js` file:
`C:\ProgramData\Anaconda3\Lib\site-packages\notebook\static\components\codemirror\mode\stata`

My `Ipython` version is 6.2.1.

Any ideas how to get it working?
Thanks again!

**Comment by TiesdeKok** [comment]
Hi!

Yes, it appears that recent changes to either `Ipython` or `Jupyter` changed the way that custom syntax highlighting is added. 

After looking in to it I believe I have found a fix. 

I have changed the code and pushed it to the GitHub repo: 49acff7e13716d7baa7cf43be1b6b7c6cef9fc0c

Could you please install this newest version and let me know whether it solves your problem?

````
pip install git+https://github.com/TiesdeKok/ipystata -U
````

**Comment by v-marinkov** [comment]
Yes! Thank you - all working great now!
