### ISSUE TITLE
handling dates

### ISSUE THREAD

**Issue by jblocher** [TiesdeKok/ipystata#33]
Dates are not handled properly when passed back and forth. For example, generate the following data in Stata:
```
clear all
set obs 50
gen date = _n +20000
format date %td
save "~/test.dta", replace
```
In Jupyter, run the following in a cell:
```
%%stata
use "~/test.dta"
drop if date < date("20141101","YMD")
tab date
```
And you get this:
```
(27 observations deleted)

       date |      Freq.     Percent        Cum.
------------+-----------------------------------
  01nov2014 |          1        4.35        4.35
  02nov2014 |          1        4.35        8.70
  03nov2014 |          1        4.35       13.04
  04nov2014 |          1        4.35       17.39
  05nov2014 |          1        4.35       21.74
  06nov2014 |          1        4.35       26.09
  07nov2014 |          1        4.35       30.43
  08nov2014 |          1        4.35       34.78
  09nov2014 |          1        4.35       39.13
  10nov2014 |          1        4.35       43.48
  11nov2014 |          1        4.35       47.83
  12nov2014 |          1        4.35       52.17
  13nov2014 |          1        4.35       56.52
  14nov2014 |          1        4.35       60.87
  15nov2014 |          1        4.35       65.22
  16nov2014 |          1        4.35       69.57
  17nov2014 |          1        4.35       73.91
  18nov2014 |          1        4.35       78.26
  19nov2014 |          1        4.35       82.61
  20nov2014 |          1        4.35       86.96
  21nov2014 |          1        4.35       91.30
  22nov2014 |          1        4.35       95.65
  23nov2014 |          1        4.35      100.00
------------+-----------------------------------
      Total |         23      100.00
```
If instead you run this:
```
%%stata -o test
use "~/test.dta"
tab date
```
Then later this:
```
%%stata -d test
drop if date < date("20141101","YMD")
tab date
```
You get this output:
```
(0 observations deleted)

       date |      Freq.     Percent        Cum.
------------+-----------------------------------
  05oct20.. |          1        2.00        2.00
  06oct20.. |          1        2.00        4.00
  07oct20.. |          1        2.00        6.00
  08oct20.. |          1        2.00        8.00
  09oct20.. |          1        2.00       10.00
  10oct20.. |          1        2.00       12.00
  11oct20.. |          1        2.00       14.00
  12oct20.. |          1        2.00       16.00
  13oct20.. |          1        2.00       18.00
  14oct20.. |          1        2.00       20.00
  15oct20.. |          1        2.00       22.00
  16oct20.. |          1        2.00       24.00
  17oct20.. |          1        2.00       26.00
  18oct20.. |          1        2.00       28.00
  19oct20.. |          1        2.00       30.00
  20oct20.. |          1        2.00       32.00
  21oct20.. |          1        2.00       34.00
  22oct20.. |          1        2.00       36.00
  23oct20.. |          1        2.00       38.00
  24oct20.. |          1        2.00       40.00
  25oct20.. |          1        2.00       42.00
  26oct20.. |          1        2.00       44.00
  27oct20.. |          1        2.00       46.00
  28oct20.. |          1        2.00       48.00
  29oct20.. |          1        2.00       50.00
  30oct20.. |          1        2.00       52.00
  31oct20.. |          1        2.00       54.00
  01nov20.. |          1        2.00       56.00
  02nov20.. |          1        2.00       58.00
  03nov20.. |          1        2.00       60.00
  04nov20.. |          1        2.00       62.00
  05nov20.. |          1        2.00       64.00
  06nov20.. |          1        2.00       66.00
  07nov20.. |          1        2.00       68.00
  08nov20.. |          1        2.00       70.00
  09nov20.. |          1        2.00       72.00
  10nov20.. |          1        2.00       74.00
  11nov20.. |          1        2.00       76.00
  12nov20.. |          1        2.00       78.00
  13nov20.. |          1        2.00       80.00
  14nov20.. |          1        2.00       82.00
  15nov20.. |          1        2.00       84.00
  16nov20.. |          1        2.00       86.00
  17nov20.. |          1        2.00       88.00
  18nov20.. |          1        2.00       90.00
  19nov20.. |          1        2.00       92.00
  20nov20.. |          1        2.00       94.00
  21nov20.. |          1        2.00       96.00
  22nov20.. |          1        2.00       98.00
  23nov20.. |          1        2.00      100.00
------------+-----------------------------------
      Total |         50      100.00
```

Something is happening in the conversion of date fields between Stata and Python. I'm an intermediate Stata user but only a beginner with Python so I'm not sure what is going on. I also know that dates are tricky things to get right across languages. 

This is a wonderful package and I'm using it anyway, but this is a pretty limiting bug.

**Comment by TiesdeKok** [comment]
Thanks for the extensive report!

There has been a long-standing bug with the way that Pandas converts dates when saving .dta files (which ipystata uses under the hood to handle data transfer). My fix, currently at least, is to detect date columns and to explicitly convert them to the `%tc` form when saving to .dta:

https://github.com/TiesdeKok/ipystata/blob/49acff7e13716d7baa7cf43be1b6b7c6cef9fc0c/ipystata/ipystata_magic.py#L287-L294

My guess is that the problem you describe stems from this conversion (particularly because your problem dates are generated as `%td`).

I will need to look into it in more detail to see what the best solution is, but maybe this already helps in the mean time.

**Comment by jblocher** [comment]
Got it. That helps and gives a nice workaround. For others who may need it, here is specifically what I did:
```
%%stata -o test
use "~/test.dta"
gen date2 = Cofd(date)
format date2 %tcDDmonCCYY
tab date2
```
This generates the expected output, same as above. I had to change the formatting to get rid of the `...` in the first column so I could read the years. 
Unfortunately, that formatting doesn't save, so I have to reset it each time, but I can keep using my `date2` variable:
```
%%stata -d test
format date2 %tcDDmonCCYY
tab date2
```
This gives the same thing after passing it to Python and back.
Now, here is what I really wanted to do:
```
%%stata -d test
drop if date2 > Cofd(date("20141031","YMD"))
format date2 %tcDDmonCCYY
tab date2
```
The trick here is that the MDY() function is a %td function so I had to convert that also. I could have done mdyhms() but prefer this way so I can easily get rid of the %tc stuff once this is fixed (preferably in pandas...).

**Comment by TiesdeKok** [comment]
It is good to hear you at least found a work-around.

I found the Pandas issue thread on this problem: https://github.com/pandas-dev/pandas/issues/12259
It appears that they did end up fixing it. 

Looking at the docs for `df.to_stata()` it says the following now:

> convert_dates : dict

> Dictionary mapping columns containing datetime types to stata internal format to use when wirting the dates. Options are ‘tc’, ‘td’, ‘tm’, ‘tw’, ‘th’, ‘tq’, ‘ty’. Column can be either an integer or a name. Datetime columns that do not have a conversion type specified will be converted to ‘tc’. Raises NotImplementedError if a datetime column has timezone information

In other words, they will always convert date columns to %tc (like my solution) unless the user explicitly specifies another format to use. 

The only way to allow ipystata to utilize this functionality would be to add an additional parameter to which you pass a dictionary with the columns and their date format. I could probably add this, but I don't know whether this would be an easier work-around compared to just converting it back to %td in Stata as mentioned in your example...

**Comment by jblocher** [comment]
At this point, I think you are correct that simplicity is more important than additional flexibility. If you begin to add more features, parameters, etc. that allow some flexibility, additional date functionality would be nice.
