### ISSUE TITLE
Dates, Months, Quarters not properly handled

### ISSUE THREAD

**Issue by ravivmg** [TiesdeKok/ipystata#34]
I have a Stata dataset with dates, months, and quarters (formated %td, %tm, %tq).

When I do "%%stata -d df" then ipystata converts all of them to %tc.

**Comment by TiesdeKok** [comment]
Yes, that is unfortunately a problem with Pandas.

See my extensive answer here: https://github.com/TiesdeKok/ipystata/issues/33

**Comment by ravivmg** [comment]
Ah, sorry, I didn't see that closed issue. I'll close this issue.
Thanks!
