### ISSUE TITLE
feature request: configure stata executable on a remote host

### ISSUE THREAD

**Issue by giupo** [TiesdeKok/ipystata#40]
It would be quite useful to have the option to configure a url like `ssh://username@remotehost:/path/to/stata` as installation path to use a remotely installed stata. 

My use case: I have a docker stack with a jupyter notebook in it and I wish I could make available Stata in it. Since I cannot put stata (for obvious reasons) into a docker container due licensing problems, being able to make ipystata work on a remote shell would be a nice-to-have.

**Comment by TiesdeKok** [comment]
That is an interesting suggestion, that seems feasible with regards to the communication with Stata, however, it will cause trouble with the input and output files. Right now the input and output data is transferred between Python/Stata using the local file system. Obviously this could all be shipped over the remote connection as well but that would be a pretty substantial revision. 

It sounds simpler to include the Stata executable into the docker container but have it access the license file from a remote location (i.e. through a local folder that is mounted into the docker container)? This way you could keep all the running bits inside the docker container and use ipystata as normal. 

Would that work?
