### ISSUE TITLE
in stata '#' or '##' means interaction terms, but in Python # means annotation.how can I create a interaction term in ipystata

### ISSUE THREAD

**Issue by LiShi2269** [TiesdeKok/ipystata#42]
in stata '#' or '##' means interaction terms, but in Python '#' means annotation. how can I create a interaction term in ipystata

**Comment by TiesdeKok** [comment]
Sorry about the delayed response, this one slipped by me. This shouldn't matter given that any code in the `%%stata` will be processed without any Python interpretation applied to it. The only thing that you might see is that Jupyter will apply Python formatting to the cell, which will make it appear as if it is commented out. But if you just run the code it should be no problem.

Please let me know if that is not what you are experiencing!
