### ISSUE TITLE
ValueError:  Fixed width strings in Stata .dta files are limited to 244 (or fewer) characters.

### ISSUE THREAD

**Issue by gcasamat** [TiesdeKok/ipystata#43]
I work with ipystata 0.4.0 and Stata 16.1 on Mac OS. 
I have imported data with the following code: 
```
%%stata -o test_df
global data_dir "/Users//`c(username)'/OneDrive/Donnees"
global period_agreg quarter
global spatial_agreg section
use "$data_dir/Airbnb/data_for_reg_impact_prices_${spatial_agreg}_${period_agreg}.dta", clear
```
It works fine: when I execute test_df.head(), I get the correct dataset. 
However when I want to go back to Stata, doing for example 
```
%%stata -d test_df 
des year
```
I get the following error message: 
```
ValueError: 
Fixed width strings in Stata .dta files are limited to 244 (or fewer)
characters.  Column 'l_idlocmut' does not satisfy this restriction. Use the
'version=117' parameter to write the newer (Stata 13 and later) format.
```

**Comment by TiesdeKok** [comment]
Hi @gcasamat, my apologies, I completely missed this issue. 

This should be an easy fix once I get around to it, the primary thing I need to figure out is the best way to implement a way to use the more recent .dta versions without breaking backwards compatibility with older Stata versions.

**Comment by gcasamat** [comment]
Hi. Many thanks for your reply. So i wait for the fix before trying your very promising package.

**Comment by TiesdeKok** [comment]
I've added the `-vr` (or `--version`) argument that you can use to specify the DTA version that you'd like to use. It defaults to 114 to remain backwards compatible, but you can change the version like so:

```
%%stata -d test_df -vr 118
des year
```

You can get this newest version (4.1) by uninstalling ipystata (`pip uninstall ipystata`) and then running:

`pip install git+https://github.com/TiesdeKok/ipystata`

It would be great if you could get back to me whether this solved your problem.

**Comment by gcasamat** [comment]
Many thanks for reacting quickly on the issue. I am currently on vacation and will not be able to make a test before a few days. I will keep you posted.

**Comment by gcasamat** [comment]
I have made a test with the corrected version of ipystata and it works fine now. Thank you!

**Comment by TiesdeKok** [comment]
Great, thanks for getting back to me. I will close this issue. 

Feel free to let me know if something else pops up.
