### ISSUE TITLE
Stata Automation

### ISSUE THREAD

**Issue by alon-muhame** [TiesdeKok/ipystata#44]
Hi;
Stata Automation:
I am trying to automate stata 13, but it has failed to register 
What i do? 
Thanks for the help

Alon

**Comment by TiesdeKok** [comment]
Hi Alon, what exactly is the problem that you are facing? When you say "it has failed to register", what is the error that you are running in to?

**Comment by alon-muhame** [comment]
Hi Ties,

It does not show any error , but when i try to call ipystata in jupyter
notebook ; then its shows an error ;

---------------------------------------------------------------------------ModuleNotFoundError
                      Traceback (most recent call
last)<ipython-input-1-a0887ce495a7> in <module>----> 1 import ipystata
c:\users\bernard
mukholi\miniconda3\lib\site-packages\ipystata\__init__.py in <module>
    6       7 if os_windows and not config.batch_mode:----> 8     from
. import ipystata_magic      9 else:     10     from . import
ipystata_magic_batch
c:\users\bernard
mukholi\miniconda3\lib\site-packages\ipystata\ipystata_magic.py in
<module>     25 import re     26 import win32com.client---> 27 import
psutil     28 import atexit     29 from datetime import datetime
ModuleNotFoundError: No module named 'psutil';


What could be the problem ? sir,



Regards
MUHAME Alon
Economics of Technology Specialist

*“We are what we repeatedly do. Excellence, then, is not an act but a
habit.”*

**Comment by TiesdeKok** [comment]
This suggests that the `psutil` module is not installed. Could you try to run the following your command line / Anaconda prompt:

`pip install psutil`

If that indicates it is already installed I'd recommend to uninstall it and reinstall it:

`pip uninstall psutil`
`pip install psutil`

**Comment by alon-muhame** [comment]
Hi Ties,

It worked , Many Thanks 
I can now import ipystata and it shows no error in Jupyter Notebook;

Feel free to share with me more materials and resources related to stata and python 

Many Thanks 


Thanks
